Solution pan gesture
ltman/SwipePopViewController pull request #13
Opened 2021-02-27 16:32 UTC by kanottonp

A solution for pan gesture without using AssociationPolicy

2021-02-27 16:47 UTC, chalermpong requested changes

2021-02-27 16:47 UTC, chalermpong commented on Sources/SwipePopViewController/SwipePopViewController.swift
> +class PanInteractivePopGesture: UIPanGestureRecognizer {
Put this class in a new file

2021-02-27 16:47 UTC, chalermpong commented on Sources/SwipePopViewController/SwipePopViewController.swift
>      }
Remove all the function that only prints debug message

2021-02-27 16:47 UTC, chalermpong commented on Sources/SwipePopViewController/SwipePopViewController.swift
> +    var firstTranslation: CGPoint = .zero
Move this variable to beginning of this class

2021-02-27 16:47 UTC, chalermpong commented on Sources/SwipePopViewController/SwipePopViewController.swift
> +    var lastBeginTime = Date()
Remove this variable (it's just for debugging)

2021-02-27 16:47 UTC, chalermpong commented on Sources/SwipePopViewController/SwipePopViewController.swift
> +        return v
This function can be removed

2021-02-27 16:47 UTC, chalermpong commented on Sources/SwipePopViewController/SwipePopViewController.swift
> +        print("deinit")
Remove

2021-02-27 16:47 UTC, chalermpong commented on Sources/SwipePopViewController/SwipePopViewController.swift
> +                                  view: UIView) {
Move this logic to `UIViewController.addSwipePopGesture`

2021-02-27 16:47 UTC, chalermpong commented on Example/SwipePopViewController/ViewController.swift
> +            addSwipePopGesture()
Please restore the old native code (`applyNativePopGesture` should not be changed)

2021-03-01 07:06 UTC, chalermpong approved these changes

2021-03-01 07:07 UTC, chalermpong commented
PR for #12

2021-03-01 07:14 UTC, camp191 approved these changes

2021-03-01 07:22 UTC, chalermpong approved these changes

2021-03-01 07:22 UTC, merged